//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Golfe.Web.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GolfeEntities : DbContext
    {
        public GolfeEntities()
            : base("name=GolfeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<areajogo> areajogo { get; set; }
        public DbSet<funcionarios> funcionarios { get; set; }
        public DbSet<maquina> maquina { get; set; }
        public DbSet<tarefasgerais> tarefasgerais { get; set; }
    }
}
