//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Golfe.Web.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class operacao
    {
        public string nome { get; set; }
        public int id { get; set; }
    }
}
