//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Golfe.Web.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tarefasgerais
    {
        public string areajogo { get; set; }
        public string operacao { get; set; }
        public string maquina { get; set; }
        public string funcionario { get; set; }
        public Nullable<System.DateTime> datainicio { get; set; }
        public int id { get; set; }
        public bool done { get; set; }
    }
}
